apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: elk
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: elk
              tier: logging
        spec:
            containers:
            - name: elk
              image: scoussy/elk:latest
              volumeMounts:
              - mountPath: /root/elasticsearch/
                name: es-volume-1
              - mountPath: /var/lib/elasticsearch/elasticsearch
                name: es-volume-2
              ports:
              - containerPort: 5601
              - containerPort: 9200
              - containerPort: 5044
              - containerPort: 5000
              - containerPort: 4560
            volumes:
            - name: es-volume-1
              emptyDir: {}
            - name: es-volume-2
              emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
    name: elk-gateway
    labels:
        app: elk
        tier: logging
spec:
    type: LoadBalancer
    ports:
    - name: web
      protocol: TCP
      port: 5601
      targetPort: 5601
    - name: logstash
      protocol: TCP
      port: 4560
      targetPort: 4560
    selector:
        app: elk
        tier: logging